local sourceRoot = (... or ".")
local Frames = dofile(sourceRoot .. "/tests/support/frames.lua")

local function AssertEqual(actual, expected)
    if actual ~= expected then
        error(("expected %s, got %s"):format(tostring(expected), tostring(actual)))
    end
end

local function AssertError(callback, ...)
    local ok, message = pcall(callback)
    AssertEqual(ok, false)
    for _, fragment in ipairs({ ... }) do
        if not tostring(message):find(fragment, 1, true) then
            error("missing error detail " .. fragment .. ": " .. tostring(message))
        end
    end
end

local parent = CreateFrame("Frame", "MockParent")
local child = Frames.Create("Button", "MockChild", parent, "ButtonTemplate")
local label = child:CreateFontString("MockLabel", "OVERLAY", "GameFontNormal")
local texture = child:CreateTexture("MockTexture", "BACKGROUND")
AssertEqual(parent:GetName(), "MockParent")
AssertEqual(child:GetParent(), parent)
AssertEqual(label:GetParent(), child)
AssertEqual(texture:GetParent(), child)
AssertEqual(parent.children[1], child)
AssertEqual(child.children[1], label)
AssertEqual(child.children[2], texture)
AssertEqual(child.template, "ButtonTemplate")
AssertEqual(label.frameType, "FontString")
AssertEqual(texture.frameType, "Texture")
AssertEqual(_G.MockLabel, label)
AssertEqual(_G.MockTexture, texture)
AssertEqual(Frames.Find("MockChild"), child)
AssertEqual(Frames.Find("MockParent/MockChild/MockLabel"), label)
AssertEqual(Frames.Find("MockLabel", child), label)
AssertEqual(Frames.Find("2", child), texture)
AssertEqual(Frames.Find("Missing"), nil)
AssertEqual(Frames.Find("MockParent/Missing"), nil)

child:SetPoint("CENTER")
Frames.AssertAnchor(child, 1, { "CENTER", parent, "CENTER", 0, 0 })
child:SetPoint("TOPLEFT", 3, -4)
Frames.AssertAnchor(child, 2, { "TOPLEFT", parent, "TOPLEFT", 3, -4 })
child:SetPoint("BOTTOMRIGHT", parent, "BOTTOMRIGHT", -5, 6)
Frames.AssertAnchor(child, 3, { "BOTTOMRIGHT", parent, "BOTTOMRIGHT", -5, 6 })
child:SetPoint("LEFT", "MockParent", "RIGHT", 7, 8)
Frames.AssertAnchor(child, 4, { "LEFT", parent, "RIGHT", 7, 8 })
child:SetPoint("RIGHT", nil, "LEFT", -7, -8)
Frames.AssertAnchor(child, 5, { "RIGHT", parent, "LEFT", -7, -8 })
child:SetPoint("TOP", parent, "BOTTOM")
Frames.AssertAnchor(child, 6, { "TOP", parent, "BOTTOM", 0, 0 })
child:SetPoint("CENTER", 10, 11)
AssertEqual(child:GetNumPoints(), 6)
local point, relative, relativePoint, x, y = child:GetPoint()
AssertEqual(point, "CENTER")
AssertEqual(relative, parent)
AssertEqual(relativePoint, "CENTER")
AssertEqual(x, 10)
AssertEqual(y, 11)
AssertEqual(child:GetPoint(7), nil)
child:ClearAllPoints()
AssertEqual(child:GetNumPoints(), 0)
for _, target in ipairs({ parent, "MockParent" }) do
    child:SetAllPoints(target)
    AssertEqual(child:GetNumPoints(), 2)
    Frames.AssertAnchor(child, 1, { "TOPLEFT", parent, "TOPLEFT", 0, 0 })
    Frames.AssertAnchor(child, 2, { "BOTTOMRIGHT", parent, "BOTTOMRIGHT", 0, 0 })
end
child:SetAllPoints()
Frames.AssertAnchor(child, 1, { "TOPLEFT", parent, "TOPLEFT", 0, 0 })
AssertError(function() child:SetPoint("CENTER", "Missing", "CENTER") end, "Missing")

for _, region in ipairs({ child, label, texture }) do
    region:SetSize(100, 20)
    Frames.AssertSize(region, 100, 20)
    region:SetWidth(120)
    region:SetHeight(30)
    AssertEqual(region:GetWidth(), 120)
    AssertEqual(region:GetHeight(), 30)
    Frames.AssertSize(region, 120, 30)
    Frames.AssertShown(region, true)
    Frames.AssertVisible(region, true)
    region:Hide()
    Frames.AssertShown(region, false)
    Frames.AssertVisible(region, false)
    region:Show()
    region:ClearAllPoints()
    region:SetPoint("CENTER")
    Frames.AssertAnchor(region, 1, { "CENTER", region:GetParent(), "CENTER", 0, 0 })
end
parent:Hide()
Frames.AssertShown(label, true)
Frames.AssertVisible(label, false)
Frames.AssertVisible(texture, false)
Frames.AssertVisible(child, false)
parent:Show()
Frames.AssertVisible(label, true)
child:SetShown(false)
Frames.AssertShown(child, false)
child:SetShown(true)
label:SetText("Team Alpha")
AssertEqual(label:GetText(), "Team Alpha")
Frames.AssertText(label, "Team Alpha")
texture:SetTexture("Interface/Test")
AssertEqual(texture.texture, "Interface/Test")
texture:SetColorTexture(0.1, 0.2, 0.3, 0.4)
AssertEqual(texture.color[4], 0.4)
label:SetFont("Fonts/Test.ttf", 14, "OUTLINE")
AssertEqual(label.font[1], "Fonts/Test.ttf")
AssertEqual(label.font[2], 14)
AssertEqual(label.font[3], "OUTLINE")
child:SetFrameLevel(12)
child:SetFrameStrata("HIGH")
child:EnableMouse(true)
AssertEqual(child:GetFrameLevel(), 12)
AssertEqual(child.frameStrata, "HIGH")
AssertEqual(child.mouseEnabled, true)

local order = {}
local function OnClick(self, button, value, last)
    AssertEqual(self, child)
    AssertEqual(button, "LeftButton")
    AssertEqual(value, nil)
    AssertEqual(last, 42)
    order[#order + 1] = "original"
end
child:SetScript("OnClick", OnClick)
AssertEqual(child:GetScript("OnClick"), OnClick)
child:HookScript("OnClick", function(self, button, value, last)
    OnClick(self, button, value, last)
    order[#order] = "hook1"
end)
child:HookScript("OnClick", function() order[#order + 1] = "hook2" end)
Frames.Fire(child, "OnClick", "LeftButton", nil, 42)
AssertEqual(table.concat(order, ","), "original,hook1,hook2")
Frames.Fire(child, "OnUnused")
child:HookScript("OnEnter", function(self) AssertEqual(self, child) end)
Frames.Fire(child, "OnEnter")
child:SetScript("OnClick", nil)
AssertEqual(child:GetScript("OnClick"), nil)
child:RegisterEvent("PLAYER_LOGIN")
child:RegisterEvent("PLAYER_LOGIN")
child:RegisterEvent("PLAYER_LOGOUT")
AssertEqual(child.events.PLAYER_LOGIN, true)
AssertEqual(child.events.PLAYER_LOGOUT, true)
child:UnregisterEvent("PLAYER_LOGIN")
AssertEqual(child.events.PLAYER_LOGIN, nil)
child:UnregisterEvent("PLAYER_LOGOUT")
AssertEqual(next(child.events), nil)

label:SetParent(parent)
AssertEqual(label:GetParent(), parent)
AssertEqual(#child.children, 1)
AssertEqual(parent.children[2], label)
label:SetParent(parent)
AssertEqual(#parent.children, 2)
label:SetParent(nil)
AssertEqual(label:GetParent(), nil)
AssertEqual(#parent.children, 1)
label:SetParent(child)
AssertError(function() parent:SetParent(child) end, "parent")
AssertError(function() child:UnimplementedMethod() end, "UnimplementedMethod", "Button", "MockChild")
AssertError(function() Frames.AssertSize(child, 9, 9) end, "MockChild", "width", "9", "120")
AssertError(function() Frames.AssertAnchor(child, 1, { "LEFT", parent, "LEFT", 0, 0 }) end, "MockChild", "anchor")
local anonymous = CreateFrame("Frame")
local another = CreateFrame("Frame")
anonymous:SetPoint("CENTER", another, "CENTER", 0, 0)
AssertError(function() Frames.AssertAnchor(anonymous, 1, { "CENTER", anonymous, "CENTER", 0, 0 }) end, "anchor")
AssertError(function() Frames.AssertShown(child, false) end, "MockChild", "shown")
AssertError(function() Frames.AssertVisible(child, false) end, "MockChild", "visible")
AssertError(function() Frames.AssertText(label, "Wrong") end, "MockLabel", "text", "Wrong")
local dump = Frames.Dump(parent)
for _, fragment in ipairs({ "MockParent", "MockChild", "Button", "shown=true", "CENTER", "120x30", "Team Alpha" }) do
    AssertEqual(dump:find(fragment, 1, true) ~= nil, true)
end

Frames.Reset()
AssertEqual(_G.MockParent, nil)
AssertEqual(_G.MockChild, nil)
AssertEqual(_G.MockLabel, nil)
AssertEqual(_G.MockTexture, nil)
AssertEqual(Frames.Find("MockParent"), nil)
AssertEqual(Frames.Dump(), "")
local previousFactory = function() end
CreateFrame = previousFactory
MockParent = "existing global"
Frames.Install()
parent = CreateFrame("Frame", "MockParent")
AssertEqual(#parent.children, 0)
AssertEqual(parent:GetNumPoints(), 0)
AssertEqual(next(parent.scripts), nil)
AssertEqual(next(parent.events), nil)
Frames.Reset()
AssertEqual(CreateFrame, previousFactory)
AssertEqual(MockParent, "existing global")
MockParent = nil

Frames.Install()
local journal = CreateFrame("Frame", "PetJournal")
journal:SetFrameLevel(50)
dofile(sourceRoot .. "/BattleBuddy/PetJournalSurface.lua")
local Surface = BattleBuddyPetJournalSurface
AssertEqual(Surface.Attach(), true)
AssertEqual(Surface.frame:GetParent(), journal)
Frames.AssertSize(Surface.frame, 310, 390)
Frames.AssertAnchor(Surface.frame, 1, { "TOPRIGHT", journal, "TOPRIGHT", -38, -42 })
AssertEqual(Surface.frame:GetFrameLevel(), 60)
Frames.AssertShown(Surface.frame, false)
Frames.AssertText(Surface.opener, "BattleBuddy")
Frames.Fire(Surface.opener, "OnClick")
Frames.AssertVisible(Surface.frame, true)
Frames.AssertText(Surface.detail, "No encounter selected. Choose an encounter when BattleBuddy content is available.")
Frames.Reset()
