BattleBuddyEncounterContent = {}

local Content = BattleBuddyEncounterContent

Content.SchemaVersion = 1
Content.ShippedContentVersion = 2

Content.Records = {
    {
        encounterID = "shipped.wod.squirt",
        origin = "shipped",
        recordRevision = 2,
        display = { fallbackLabel = "Squirt", locale = "enUS" },
        selectors = { { npcID = 79179 } },
        content = {
            expansion = "Warlords of Draenor",
            category = "tamer",
            headerID = "menagerie",
            mapID = 582,
            zone = "Menagerie",
            questID = 37644,
            enemyPets = { { speciesID = 1400 }, { speciesID = 1401 }, { speciesID = 1402 } },
            locations = {},
            repeatability = "daily",
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Squirt encounter." },
    },
    {
        encounterID = "shipped.legion.amalia",
        origin = "shipped",
        recordRevision = 2,
        display = { fallbackLabel = "Amalia", locale = "enUS" },
        selectors = { { npcID = 107489 } },
        content = {
            expansion = "Legion",
            category = "world-quest",
            headerID = 627,
            mapID = 627,
            zone = "Dalaran",
            questID = 42442,
            enemyPets = { { speciesID = 1905 }, { speciesID = 1904 }, { speciesID = 1906 } },
            locations = {},
            repeatability = "daily",
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Amalia encounter." },
    },
    {
        encounterID = "shipped.legion.sir-galveston",
        origin = "shipped",
        recordRevision = 2,
        display = { fallbackLabel = "Sir Galveston", locale = "enUS" },
        selectors = { { npcID = 99182 } },
        content = {
            expansion = "Legion",
            category = "world-quest",
            headerID = 627,
            mapID = 627,
            zone = "Dalaran",
            questID = 40298,
            enemyPets = { { speciesID = 1795 }, { speciesID = 1796 }, { speciesID = 1797 } },
            locations = {},
            repeatability = "daily",
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Sir Galveston encounter." },
    },
    {
        encounterID = "shipped.dragonflight.haniko",
        origin = "shipped",
        recordRevision = 1,
        display = { fallbackLabel = "Haniko", locale = "enUS" },
        selectors = { { npcID = 196264 } },
        content = {
            expansion = "Dragonflight",
            category = "world-quest",
            headerID = 2022,
            mapID = 2022,
            zone = "The Waking Shores",
            questID = 66551,
            enemyPets = { { speciesID = 3387 }, { speciesID = 3386 }, { speciesID = 3388 } },
            locations = {},
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Haniko encounter." },
    },
    {
        encounterID = "shipped.pandaria.no-no",
        origin = "shipped",
        recordRevision = 1,
        display = { fallbackLabel = "No-No", locale = "enUS" },
        selectors = { { npcID = 68559 } },
        content = {
            expansion = "Mists of Pandaria",
            category = "legendary",
            headerID = "beasts-of-fable",
            mapID = 390,
            zone = "Pandaria",
            questID = 32869,
            enemyPets = { { speciesID = 1188 } },
            locations = {},
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, No-No encounter." },
    },
    {
        encounterID = "shipped.wrath.major-payne",
        origin = "shipped",
        recordRevision = 1,
        display = { fallbackLabel = "Major Payne", locale = "enUS" },
        selectors = { { npcID = 66675 } },
        content = {
            expansion = "Wrath of the Lich King",
            category = "tamer",
            headerID = 113,
            mapID = 118,
            zone = "Northrend",
            questID = 31935,
            enemyPets = { { speciesID = 979 }, { speciesID = 978 }, { speciesID = 977 } },
            locations = {},
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Major Payne encounter." },
    },
    {
        encounterID = "shipped.legion.son-of-skum",
        origin = "shipped",
        recordRevision = 1,
        display = { fallbackLabel = "Son of Skum", locale = "enUS" },
        selectors = { { npcID = 116789 } },
        content = {
            expansion = "Legion",
            category = "dungeon",
            headerID = 825,
            mapID = 825,
            zone = "Wailing Caverns",
            questID = 45539,
            enemyPets = { { speciesID = 1990 }, { speciesID = 1987 }, { speciesID = 1989 } },
            locations = {},
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Son of Skum encounter." },
    },
    {
        encounterID = "shipped.legion.budding-everliving-spore",
        origin = "shipped",
        recordRevision = 1,
        display = { fallbackLabel = "Budding Everliving Spore", locale = "enUS" },
        selectors = { { npcID = 116795 } },
        content = {
            expansion = "Legion",
            category = "dungeon",
            headerID = 825,
            mapID = 825,
            zone = "Wailing Caverns",
            questID = 45539,
            enemyPets = { { speciesID = 1996 }, { speciesID = 1987 }, { speciesID = 1988 } },
            locations = {},
        },
        support = { state = "unverified", reasons = { "Client availability has not yet been verified." } },
        provenance = { "Individually recorded game facts; Akolus targetData.lua, Budding Everliving Spore encounter." },
    },
}

function Content.BuildCatalogInput()
    return {
        schemaVersion = Content.SchemaVersion,
        shippedContentVersion = Content.ShippedContentVersion,
        catalogRevision = Content.ShippedContentVersion,
        records = Content.Records,
    }
end
